### PR TITLE
Added ligatures for <-, ->; Bumped to 2.011

### PR DESCRIPTION
**Pull request by appsforartists**
As requested by @sleepiejohn, I added simple ligatures for `<-` and `->`.  It also looks like `>=` was off-canvas in your bold version, so I fixed that.  Finally, I bumped to 2.011.

Please review.

### CODE REVIEW

**Comment by alexeiva** [comment]
Ok. You have updated `(){}` in Regular but not in Bold:


screen shot 2018-03-08 at 1 54 42 pm

**Comment by appsforartists** [comment]
Good catch.  I should bump those up.  (Should probably also make bold versions of the ligs)

**Comment by alexeiva** [comment]
Not necessarily. Not all symbols get a Bold version.

inco

I should update `✓♠` to be identical in both styles after your commit.

**Comment by appsforartists** [comment]
Fixed the bold positioning, and enboldened the JS ligatures.

**Comment by alexeiva** [comment]
Thank you for contributing, release [v2.012](https://github.com/alexeiva/Inconsolata/releases/tag/v2.012) is out.

**Pull request merged**
